# Generated by Django 5.1.2 on 2025-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('program', models.CharField(choices=[('Education', 'Education'), ('Healthcare Outreach', 'Healthcare Outreach'), ('Women Empowerment', 'Women Empowerment'), ('Environmental Sustainability', 'Environmental Sustainability')], max_length=50)),
                ('relevant_experience', models.TextField()),
                ('availability', models.CharField(max_length=100)),
                ('reasons', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('Volunteer',),
                'verbose_name_plural': 'Volunteer',
            },
        ),
    ]
