# Generated by Django 5.1.2 on 2025-11-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloom_Africa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('contacts_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('partnership_type', models.CharField(choices=[('Corporate Partnerships', 'Corporate Partnerships'), ('NGO Collaborations', 'NGO Collaborations'), ('Government Partnerships', 'Government Partnerships'), ('Academic Institutions', 'Academic Institutions')], max_length=50)),
                ('program_type', models.CharField(choices=[('Education', 'Education'), ('Healthcare Outreach', 'Healthcare Outreach'), ('Women Empowerment', 'Women Empowerment'), ('Environmental Sustainability', 'Environmental Sustainability')], max_length=50)),
                ('partnership_goals', models.TextField()),
                ('values', models.TextField()),
                ('preffered_timeline', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Partnerships',
                'verbose_name_plural': 'Partnerships',
            },
        ),
    ]
