# Generated by Django 5.1.2 on 2025-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloom_Africa', '0002_partnerships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('program', models.CharField(choices=[('Education', 'Education'), ('Healthcare Outreach', 'Healthcare Outreach'), ('Women Empowerment', 'Women Empowerment'), ('Environmental Sustainability', 'Environmental Sustainability')], max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('dedication', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donations',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
