# Generated by Django 5.1.2 on 2025-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloom_Africa', '0003_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('Education', 'Education'), ('Healthcare Outreach', 'Healthcare Outreach'), ('Women Empowerment', 'Women Empowerment'), ('Environmental Sustainability', 'Environmental Sustainability')], max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
