# Generated by Django 5.1.2 on 2025-11-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloom_Africa', '0004_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
    ]
